export const ACCOUNT_NUMBER_REQUEST = 'ACCOUNT_NUMBER_REQUEST';
export const ACCOUNT_NUMBER_SUCCESS = 'ACCOUNT_NUMBER_SUCCESS';
export const ACCOUNT_NUMBER_FAILURE = 'ACCOUNT_NUMBER_FAILURE';

export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE';

export const FETCH_ACCOUNT_BALANCE_REQUEST = 'FETCH_ACCOUNT_BALANCE_REQUEST';
export const FETCH_ACCOUNT_BALANCE_SUCCESS = 'FETCH_ACCOUNT_BALANCE_SUCCESS';
export const FETCH_ACCOUNT_BALANCE_FAILURE = 'FETCH_ACCOUNT_BALANCE_FAILURE';